#!/bin/bash
# Script to test the checker with a new randomly corrupted image.

cd dfscorrupt
./run
cd ..

make clean && make
echo "Copying test image..."
cp images/corrupted/corrupted.dfs .
echo "Running dfsck..."
./dfsck corrupted.dfs
